#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

#exec-once = $terminal
#exec-once = nm-applet &
exec-once = waybar
exec-once = hyprpaper
# Notification daemon
exec-once = mako
exec-once = gentoo-pipewire-launcher

source = modules/env.conf
source = modules/binds.conf
source = modules/general.conf
source = modules/input.conf
source = modules/monitors.conf
source = modules/rules.conf
source = modules/permissions.conf
